#                                           numpy 练习题

### numpy 的array操作

#### 1.导入numpy库

In [2]:
import numpy

#### 2.建立一个一维数组 a 初始化为[4,5,6], (1)输出a 的类型（type）(2)输出a的各维度的大小（shape）(3)输出 a的第一个元素（值为4）

In [3]:
a = numpy.array([4, 5, 6])
# 输出a的类型
print(type(a))
# 输出a的各维度大小（shape）
print(a.shape)
# 输出a的第一个元素
print(a[0])

<class 'numpy.ndarray'>
(3,)
4


#### 3.建立一个二维数组 b,初始化为 [ [4, 5, 6],[1, 2, 3]] (1)输出各维度的大小（shape）(2)输出 b(0,0)，b(0,1),b(1,1) 这三个元素（对应值分别为4,5,2）

In [4]:
b = numpy.array([[4, 5, 6], [1, 2, 3]])
# 输出各维度大小（shape）
print(b.shape)
# 输出 b(0,0), b(0,1), b(1,1)
print(b[0, 0], b[0, 1], b[1, 1])

(2, 3)
4 5 2


#### 4.  (1)建立一个全0矩阵 a, 大小为 3x3; 类型为整型（提示: dtype = int）(2)建立一个全1矩阵b,大小为4x5;  (3)建立一个单位矩阵c ,大小为4x4; (4)生成一个随机数矩阵d,大小为 3x2.

In [5]:
# (1)建立全0矩阵，大小为3x3，类型为整型
a = numpy.zeros((3, 3), dtype=int)
print(a)

# (2)建立全1矩阵，大小为4x5
b = numpy.ones((4, 5))
print(b)

# (3)建立单位矩阵，大小为4x4
c = numpy.eye(4)
print(c)

# (4)生成随机数矩阵，大小为3x2
d = numpy.random.random((3, 2))
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.02071426 0.32496009]
 [0.9309314  0.92370567]
 [0.60814895 0.48554151]]


#### 5. 建立一个数组 a,(值为[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] ) ,(1)打印a; (2)输出  下标为(2,3),(0,0) 这两个数组元素的值

In [ ]:
a = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# (1)打印a
print(a)

# (2)输出下标为(2,3)和(0,0)这两个元素的值
print(a[2, 3])
print(a[0, 0])

#### 6.把上一题的 a数组的 0到1行 2到3列，放到b里面去，（此处不需要从新建立a,直接调用即可）(1),输出b;(2) 输出b 的（0,0）这个元素的值

In [ ]:
# 使用第5题的a数组
b = a[0:2, 2:4]
# (1)输出b
print(b)

# (2)输出b的(0,0)元素的值
print(b[0, 0])

 #### 7. 把第5题中数组a的最后两行所有元素放到 c中，（提示： a[1:2, :]）(1)输出 c ; (2) 输出 c 中第一行的最后一个元素（提示，使用 -1                 表示最后一个元素）

In [ ]:
# 使用第5题的a数组
c = a[1:3, :]
# (1)输出c
print(c)

# (2)输出c中第一行的最后一个元素
print(c[0, -1])

#### 8.建立数组a,初始化a为[[1, 2], [3, 4], [5, 6]]，输出 （0,0）（1,1）（2,0）这三个元素（提示： 使用 print(a[[0, 1, 2], [0, 1, 0]]) ）

In [ ]:
a = numpy.array([[1, 2], [3, 4], [5, 6]])
# 输出(0,0)(1,1)(2,0)这三个元素
print(a[[0, 1, 2], [0, 1, 0]])

#### 9.建立矩阵a ,初始化为[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]，输出(0,0),(1,2),(2,0),(3,1) (提示使用 b = np.array([0, 2, 0, 1])                     print(a[np.arange(4), b]))

In [ ]:
a = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = numpy.array([0, 2, 0, 1])
print(a[numpy.arange(4), b])

#### 10.对9 中输出的那四个元素，每个都加上10，然后重新输出矩阵a.(提示： a[np.arange(4), b] += 10 ）

In [ ]:
# 使用第9题的a和b
a[numpy.arange(4), b] += 10
print(a)

### array 的数学运算

#### 11.  执行 x = np.array([1, 2])，然后输出 x 的数据类型

In [ ]:
x = numpy.array([1, 2])
print(x.dtype)

#### 12.执行 x = np.array([1.0, 2.0]) ，然后输出 x 的数据类类型

In [ ]:
x = numpy.array([1.0, 2.0])
print(x.dtype)

#### 13.执行 x = np.array([[1, 2], [3, 4]], dtype=np.float64) ，y = np.array([[5, 6], [7, 8]], dtype=np.float64)，然后输出 x+y ,和 np.add(x,y)

In [ ]:
x = numpy.array([[1, 2], [3, 4]], dtype=numpy.float64)
y = numpy.array([[5, 6], [7, 8]], dtype=numpy.float64)
# 输出x+y
print(x + y)
# 输出np.add(x,y)
print(numpy.add(x, y))

#### 14. 利用 13题目中的x,y 输出 x-y 和 np.subtract(x,y)

In [ ]:
# 使用第13题的x,y
print(x - y)
print(numpy.subtract(x, y))

#### 15. 利用13题目中的x，y 输出 x*y ,和 np.multiply(x, y) 还有  np.dot(x,y),比较差异。然后自己换一个不是方阵的试试。

In [ ]:
# 使用第13题的x,y
print("x*y (element-wise):")
print(x * y)
print("\nnp.multiply(x, y):")
print(numpy.multiply(x, y))
print("\nnp.dot(x, y) (matrix multiplication):")
print(numpy.dot(x, y))

# 使用非方阵测试
x2 = numpy.array([[1, 2, 3], [4, 5, 6]], dtype=numpy.float64)  # 2x3
y2 = numpy.array([[1, 2], [3, 4], [5, 6]], dtype=numpy.float64)  # 3x2
print("\n使用非方阵:")
print("x2*y2 (element-wise)失败因为形状不同")
print("np.dot(x2, y2) (2x3 dot 3x2 -> 2x2):")
print(numpy.dot(x2, y2))

#### 16. 利用13题目中的x,y,输出 x / y .(提示 ： 使用函数 np.divide())

In [ ]:
# 使用第13题的x,y
print(numpy.divide(x, y))

#### 17. 利用13题目中的x,输出 x的 开方。(提示： 使用函数 np.sqrt() )

In [ ]:
# 使用第13题的x
print(numpy.sqrt(x))

#### 18.利用13题目中的x,y ,执行 print(x.dot(y)) 和 print(np.dot(x,y))

In [ ]:
# 使用第13题的x,y
print(x.dot(y))
print(numpy.dot(x, y))

##### 19.利用13题目中的 x,进行求和。提示：输出三种求和 (1)print(np.sum(x)):   (2)print(np.sum(x，axis =0 ));   (3)print(np.sum(x,axis = 1))

In [ ]:
# 使用第13题的x
print("总求和:")
print(numpy.sum(x))
print("\n按行求和（axis=0）:")
print(numpy.sum(x, axis=0))
print("\n按列求和（axis=1）:")
print(numpy.sum(x, axis=1))

#### 20.利用13题目中的 x,进行求平均数（提示：输出三种平均数(1)print(np.mean(x)) (2)print(np.mean(x,axis = 0))(3) print(np.mean(x,axis =1))）

In [ ]:
# 使用第13题的x
print("总平均数:")
print(numpy.mean(x))
print("\n按行平均（axis=0）:")
print(numpy.mean(x, axis=0))
print("\n按列平均（axis=1）:")
print(numpy.mean(x, axis=1))

#### 21.利用13题目中的x，对x 进行矩阵转置，然后输出转置后的结果，（提示： x.T 表示对 x 的转置）

In [ ]:
# 使用第13题的x
print(x.T)

#### 22.利用13题目中的x,求e的指数（提示： 函数 np.exp()）

In [ ]:
# 使用第13题的x
print(numpy.exp(x))

#### 23.利用13题目中的 x,求值最大的下标（提示(1)print(np.argmax(x)) ,(2) print(np.argmax(x, axis =0))(3)print(np.argmax(x),axis =1))

In [ ]:
# 使用第13题的x
print("全局最大值下标:")
print(numpy.argmax(x))
print("\n按行最大值下标（axis=0）:")
print(numpy.argmax(x, axis=0))
print("\n按列最大值下标（axis=1）:")
print(numpy.argmax(x, axis=1))

#### 24,画图，y=x*x 其中 x = np.arange(0, 100, 0.1) （提示这里用到  matplotlib.pyplot 库）

In [ ]:
import matplotlib.pyplot as plt

x = numpy.arange(0, 100, 0.1)
y = x * x

plt.figure(figsize=(10, 6))
plt.plot(x, y)
plt.xlabel('x')
plt.ylabel('y = x*x')
plt.title('二次函数')
plt.grid(True)
plt.show()

#### 25.画图。画正弦函数和余弦函数， x = np.arange(0, 3 * np.pi, 0.1)(提示：这里用到 np.sin() np.cos() 函数和 matplotlib.pyplot 库)

In [ ]:
import matplotlib.pyplot as plt

x = numpy.arange(0, 3 * numpy.pi, 0.1)
y_sin = numpy.sin(x)
y_cos = numpy.cos(x)

plt.figure(figsize=(10, 6))
plt.plot(x, y_sin, label='sin(x)', color='blue')
plt.plot(x, y_cos, label='cos(x)', color='red')
plt.xlabel('x')
plt.ylabel('y')
plt.title('正弦函数和余弦函数')
plt.legend()
plt.grid(True)
plt.show()